version: '3.7'
services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  movie_db:
    build: ./movie-service-bd
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
      - ./movie-service-bd:/docker-entrypoint-initdb.d

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev

  cast_db:
    build: ./cast-service-bd
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
      - ./cast-service-bd:/docker-entrypoint-initdb.d

  nginx:
    build: ./ngix-conf
    ports:
      - "8080:8080"
    volumes:
      - ./ngix-conf/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast: