CREATE TABLE movies (
    id       integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(50),
    plot        varchar(250),
    genres      VARCHAR[],
    casts_id    integer[]
);
